name: Build PyPI registiry
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3"
      - uses: actions/checkout@v2
        with:
          ref: "pages"

      - run: rm -rf packages

      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: "packages"

      - run: rm -rf packages/.git

      - name: Install dumb-pypi
        run: python3 -m pip install dumb-pypi

      - name: Build PyPI
        run: |
          find . -name "*.whl" -printf "%f\n" > ./packages/packages.txt
          dumb-pypi \
            --package-list ./packages/packages.txt \
            --packages-url https://tales-pw.github.io/PyPI/packages/ \
            --output-dir .

      - name: Update github pages
        run: |
          git add --all
          git config --local user.email "pypi@tales.pw"
          git config --local user.name "pypi"
          git commit -m "rebuild index"
          git push
