name: Build PyPI registiry
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3"
      - uses: actions/checkout@v2
        with:
          ref: "master"
          path: "packages"
      - uses: actions/checkout@v2
        with:
          ref: "pages"
          path: "pages"

      - name: Install dumb-pypi
        run: python3 -m pip install dumb-pypi

      - name: Build PyPI
        run: |
          dumb-pypi \
            --package-list ./packages/packages.txt \
            --packages-url https://tales-pw.github.io/PyPI/packages/ \
            --output-dir ./pages